fn main() {
    windows::build! {
        Windows::Win32::UI::WindowsAndMessaging::{
            MessageBoxA,
            EnumWindows,
            GetWindowTextW,
            GetWindowRect,
            SetWindowPos,
            HWND_TOP,
            SendMessageCallbackA,
            SendMessageA,
            SendMessageW,
            WM_KEYDOWN,
            WM_KEYUP,
            WM_SYSKEYDOWN,
            WM_SYSKEYUP,
            WM_CHAR,
            SetForegroundWindow,
            VK_TAB,
            VK_LBUTTON
        },
        Windows::Win32::UI::KeyboardAndMouseInput::{
            INPUT,
            SendInput,
            INPUT_TYPE,
            MOUSEINPUT,
            MOUSE_EVENT_FLAGS,
            SetActiveWindow
        },
    };
}
